SET local check_function_bodies = off;

CREATE ROLE "app_admin" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS;

CREATE ROLE "app_content_manager" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS;

CREATE ROLE "app_subscriber" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS;

CREATE ROLE "app_support" WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS;

GRANT "app_admin" TO "postgres" WITH ADMIN OPTION;

GRANT "app_content_manager" TO "postgres" WITH ADMIN OPTION;

GRANT "app_subscriber" TO "postgres" WITH ADMIN OPTION;

GRANT "app_support" TO "postgres" WITH ADMIN OPTION;

CREATE TABLE "public"."content_license" (
  "license_id"      integer                GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "licensor_name"   character varying(100) NOT NULL,
  "expiration_date" date                   NOT NULL,
  "region"          character varying(50)  NOT NULL,
  CONSTRAINT "content_license_pkey" PRIMARY KEY (license_id)
);

ALTER TABLE "public"."content_license"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."content" (
  "content_id"   integer                  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "genre_id"     integer                  NOT NULL,
  "license_id"   integer                  NOT NULL,
  "title"        character varying(150)   NOT NULL,
  "description"  text                     NOT NULL,
  "release_date" date                     NOT NULL,
  "director"     character varying(100),
  "cast_info"    text,
  "synopsis"     text                     NOT NULL,
  "age_rating"   character varying(20)    NOT NULL,
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  "deleted_at"   timestamp with time zone,
  CONSTRAINT "content_pkey" PRIMARY KEY (content_id)
);

ALTER TABLE "public"."content"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."episodes" (
  "episode_id"     integer                GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "season_id"      integer                NOT NULL,
  "episode_number" integer                NOT NULL,
  "episode_title"  character varying(150) NOT NULL,
  "duration"       integer                NOT NULL,
  "release_date"   date                   NOT NULL,
  CONSTRAINT "episodes_duration_check" CHECK ((duration > 0)),
  CONSTRAINT "episodes_pkey" PRIMARY KEY (episode_id),
  CONSTRAINT "episodes_season_id_episode_number_key" UNIQUE (season_id, episode_number)
);

ALTER TABLE "public"."episodes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."favorites" (
  "fav_id"     integer                  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"    integer                  NOT NULL,
  "content_id" integer                  NOT NULL,
  "date_added" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "favorites_pkey" PRIMARY KEY (fav_id),
  CONSTRAINT "favorites_user_id_content_id_key" UNIQUE (user_id, content_id)
);

ALTER TABLE "public"."favorites"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."feedback" (
  "feedback_id"  integer                  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"      integer                  NOT NULL,
  "subject"      character varying(150)   NOT NULL,
  "message"      text                     NOT NULL,
  "created_date" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "feedback_pkey" PRIMARY KEY (feedback_id)
);

ALTER TABLE "public"."feedback"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."genre" (
  "genre_id"   integer               GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "genre_name" character varying(50) NOT NULL,
  CONSTRAINT "genre_genre_name_key" UNIQUE (genre_name),
  CONSTRAINT "genre_pkey" PRIMARY KEY (genre_id)
);

ALTER TABLE "public"."genre"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."members" (
  "member_id"       integer                  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "subscription_id" integer                  NOT NULL,
  "user_id"         integer                  NOT NULL,
  "relationship"    character varying(50)    NOT NULL,
  "date_added"      timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "members_pkey" PRIMARY KEY (member_id)
);

ALTER TABLE "public"."members"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."merchandise_product" (
  "product_id"   integer                GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_name" character varying(100) NOT NULL,
  "category"     character varying(50)  NOT NULL,
  "price"        numeric(10,2)          NOT NULL,
  CONSTRAINT "merchandise_product_pkey" PRIMARY KEY (product_id),
  CONSTRAINT "merchandise_product_price_check" CHECK ((price >= (0)::numeric))
);

ALTER TABLE "public"."merchandise_product"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."merchandise_transaction" (
  "transaction_id" integer                  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"        integer                  NOT NULL,
  "product_id"     integer                  NOT NULL,
  "quantity"       integer                  NOT NULL,
  "total_amount"   numeric(10,2)            NOT NULL,
  "created_at"     timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "merchandise_transaction_pkey" PRIMARY KEY (transaction_id),
  CONSTRAINT "merchandise_transaction_quantity_check" CHECK ((quantity > 0)),
  CONSTRAINT "merchandise_transaction_total_amount_check" CHECK ((total_amount >= (0)::numeric))
);

ALTER TABLE "public"."merchandise_transaction"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."plans" (
  "plan_id"       integer               GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "plan_name"     character varying(50) NOT NULL,
  "max_members"   integer               NOT NULL,
  "monthly_price" numeric(10,2)         NOT NULL,
  "is_active"     boolean               NOT NULL DEFAULT true,
  CONSTRAINT "plans_max_members_check" CHECK ((max_members > 0)),
  CONSTRAINT "plans_monthly_price_check" CHECK ((monthly_price >= (0)::numeric)),
  CONSTRAINT "plans_pkey" PRIMARY KEY (plan_id),
  CONSTRAINT "plans_plan_name_key" UNIQUE (plan_name)
);

ALTER TABLE "public"."plans"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."profiles" (
  "profile_id"   integer                  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"      integer                  NOT NULL,
  "profile_name" character varying(50)    NOT NULL,
  "avatar_url"   character varying(255),
  "device"       character varying(100),
  "created_at"   timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "profiles_pkey" PRIMARY KEY (profile_id),
  CONSTRAINT "uq_profiles_user_id" UNIQUE (user_id)
);

ALTER TABLE "public"."profiles"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."review" (
  "review_id"      integer                  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"        integer                  NOT NULL,
  "content_id"     integer                  NOT NULL,
  "rating_value"   numeric(2,1)             NOT NULL,
  "review_comment" text,
  "review_date"    timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "review_pkey" PRIMARY KEY (review_id),
  CONSTRAINT "review_rating_value_check" CHECK (((rating_value >= (0)::numeric) AND (rating_value <= (5)::numeric))),
  CONSTRAINT "review_user_id_content_id_key" UNIQUE (user_id, content_id)
);

ALTER TABLE "public"."review"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."season" (
  "season_id"     integer                GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "content_id"    integer                NOT NULL,
  "season_number" integer                NOT NULL,
  "season_title"  character varying(150),
  "release_date"  date                   NOT NULL,
  CONSTRAINT "season_content_id_season_number_key" UNIQUE (content_id, season_number),
  CONSTRAINT "season_pkey" PRIMARY KEY (season_id)
);

ALTER TABLE "public"."season"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."subscriptions" (
  "subscription_id"      integer                  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "subscription_user_id" integer                  NOT NULL,
  "plan_id"              integer                  NOT NULL,
  "start_date"           date                     NOT NULL DEFAULT CURRENT_DATE,
  "end_date"             date,
  "created_at"           timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "subscriptions_check" CHECK (((end_date IS NULL) OR (end_date >= start_date))),
  CONSTRAINT "subscriptions_pkey" PRIMARY KEY (subscription_id)
);

ALTER TABLE "public"."subscriptions"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."users" (
  "user_id"       integer                  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "full_name"     character varying(100)   NOT NULL,
  "email"         character varying(100)   NOT NULL,
  "password_hash" character varying(255),
  "phone_number"  character varying(20),
  "date_of_birth" date,
  "created_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"    timestamp with time zone NOT NULL DEFAULT now(),
  "deleted_at"    timestamp with time zone,
  CONSTRAINT "users_email_key" UNIQUE (email),
  CONSTRAINT "users_pkey" PRIMARY KEY (user_id)
);

CREATE TABLE "public"."view_history" (
  "history_id"          integer                  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"             integer                  NOT NULL,
  "content_id"          integer                  NOT NULL,
  "episode_id"          integer,
  "watch_date"          timestamp with time zone NOT NULL DEFAULT now(),
  "progress_percentage" numeric(5,2)             NOT NULL DEFAULT 0,
  CONSTRAINT "view_history_pkey" PRIMARY KEY (history_id),
  CONSTRAINT "view_history_progress_percentage_check" CHECK (((progress_percentage >= (0)::numeric) AND (progress_percentage <= (100)::numeric)))
);

ALTER TABLE "public"."view_history"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."watch_list" (
  "list_id"    integer                  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id"    integer                  NOT NULL,
  "content_id" integer                  NOT NULL,
  "episode_id" integer,
  "progress"   numeric(5,2)             DEFAULT 0,
  "date_added" timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "watch_list_pkey" PRIMARY KEY (list_id),
  CONSTRAINT "watch_list_progress_check" CHECK (((progress >= (0)::numeric) AND (progress <= (100)::numeric))),
  CONSTRAINT "watch_list_user_id_content_id_key" UNIQUE (user_id, content_id)
);

ALTER TABLE "public"."watch_list"
  ENABLE ROW LEVEL SECURITY;

CREATE TYPE "public"."account_status_enum" AS ENUM (
  'active',
  'deactivated',
  'suspended'
);

ALTER TABLE "public"."users"
  ADD COLUMN "account_status" public.account_status_enum NOT NULL DEFAULT 'active'::public.account_status_enum;

CREATE TYPE "public"."content_type_enum" AS ENUM (
  'movie',
  'series'
);

ALTER TABLE "public"."content"
  ADD COLUMN "type" public.content_type_enum NOT NULL;

CREATE TYPE "public"."listing_status_enum" AS ENUM (
  'active',
  'sold_out',
  'removed'
);

ALTER TABLE "public"."merchandise_product"
  ADD COLUMN "listing_status" public.listing_status_enum NOT NULL DEFAULT 'active'::public.listing_status_enum;

CREATE TYPE "public"."subscription_status" AS ENUM (
  'active',
  'expired',
  'cancelled',
  'past_due'
);

ALTER TABLE "public"."subscriptions"
  ADD COLUMN "status" public.subscription_status NOT NULL DEFAULT 'active'::public.subscription_status;

CREATE TYPE "public"."watchlist_status_enum" AS ENUM (
  'planned',
  'in_progress',
  'completed'
);

ALTER TABLE "public"."watch_list"
  ADD COLUMN "watchlist_status" public.watchlist_status_enum NOT NULL DEFAULT 'planned'::public.watchlist_status_enum;

CREATE OR REPLACE FUNCTION public.current_app_user_id()
  RETURNS integer
  LANGUAGE sql
  STABLE
  SET search_path TO 'public'
  AS $function$
    select nullif(current_setting('app.current_user_id', true), '')::integer;
$function$;

CREATE OR REPLACE FUNCTION public.is_admin()
  RETURNS boolean
  LANGUAGE sql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
  SELECT EXISTS (
    SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin'
  );
$function$;

CREATE OR REPLACE FUNCTION public.set_updated_at()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SET search_path TO 'public'
  AS $function$
begin
    new.updated_at = now();
    return new;
end;
$function$;

ALTER TABLE "public"."content"
  ADD CONSTRAINT "content_license_id_fkey" FOREIGN KEY (license_id) REFERENCES public.content_license(license_id);

ALTER TABLE "public"."favorites"
  ADD CONSTRAINT "favorites_content_id_fkey" FOREIGN KEY (content_id) REFERENCES public.content(content_id) ON DELETE CASCADE;

ALTER TABLE "public"."content"
  ADD CONSTRAINT "content_genre_id_fkey" FOREIGN KEY (genre_id) REFERENCES public.genre(genre_id);

ALTER TABLE "public"."merchandise_transaction"
  ADD CONSTRAINT "merchandise_transaction_product_id_fkey" FOREIGN KEY (product_id) REFERENCES public.merchandise_product(product_id);

ALTER TABLE "public"."review"
  ADD CONSTRAINT "review_content_id_fkey" FOREIGN KEY (content_id) REFERENCES public.content(content_id) ON DELETE CASCADE;

ALTER TABLE "public"."season"
  ADD CONSTRAINT "season_content_id_fkey" FOREIGN KEY (content_id) REFERENCES public.content(content_id) ON DELETE CASCADE;

ALTER TABLE "public"."episodes"
  ADD CONSTRAINT "episodes_season_id_fkey" FOREIGN KEY (season_id) REFERENCES public.season(season_id) ON DELETE CASCADE;

ALTER TABLE "public"."members"
  ADD CONSTRAINT "members_subscription_id_fkey" FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(subscription_id) ON DELETE CASCADE;

ALTER TABLE "public"."subscriptions"
  ADD CONSTRAINT "subscriptions_plan_id_fkey" FOREIGN KEY (plan_id) REFERENCES public.plans(plan_id);

ALTER TABLE "public"."favorites"
  ADD CONSTRAINT "favorites_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

ALTER TABLE "public"."feedback"
  ADD CONSTRAINT "feedback_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

ALTER TABLE "public"."members"
  ADD CONSTRAINT "members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

ALTER TABLE "public"."merchandise_transaction"
  ADD CONSTRAINT "merchandise_transaction_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

ALTER TABLE "public"."profiles"
  ADD CONSTRAINT "profiles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

ALTER TABLE "public"."review"
  ADD CONSTRAINT "review_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

ALTER TABLE "public"."subscriptions"
  ADD CONSTRAINT "subscriptions_subscription_user_id_fkey" FOREIGN KEY (subscription_user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

ALTER TABLE "public"."view_history"
  ADD CONSTRAINT "view_history_content_id_fkey" FOREIGN KEY (content_id) REFERENCES public.content(content_id) ON DELETE CASCADE;

ALTER TABLE "public"."view_history"
  ADD CONSTRAINT "view_history_episode_id_fkey" FOREIGN KEY (episode_id) REFERENCES public.episodes(episode_id) ON DELETE CASCADE;

ALTER TABLE "public"."view_history"
  ADD CONSTRAINT "view_history_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

ALTER TABLE "public"."watch_list"
  ADD CONSTRAINT "watch_list_content_id_fkey" FOREIGN KEY (content_id) REFERENCES public.content(content_id) ON DELETE CASCADE;

ALTER TABLE "public"."watch_list"
  ADD CONSTRAINT "watch_list_episode_id_fkey" FOREIGN KEY (episode_id) REFERENCES public.episodes(episode_id) ON DELETE CASCADE;

ALTER TABLE "public"."watch_list"
  ADD CONSTRAINT "watch_list_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

CREATE INDEX idx_content_genre ON public.content USING btree (genre_id);

CREATE INDEX idx_content_license ON public.content USING btree (license_id);

CREATE INDEX idx_content_title ON public.content USING gin (to_tsvector('english'::regconfig, (title)::text));

CREATE INDEX idx_members_subscription ON public.members USING btree (subscription_id);

CREATE INDEX idx_merch_txn_product ON public.merchandise_transaction USING btree (product_id);

CREATE INDEX idx_merch_txn_user ON public.merchandise_transaction USING btree (user_id);

CREATE INDEX idx_subscriptions_user ON public.subscriptions USING btree (subscription_user_id);

CREATE INDEX idx_view_history_content ON public.view_history USING btree (content_id);

CREATE INDEX idx_view_history_user ON public.view_history USING btree (user_id);

CREATE UNIQUE INDEX uq_one_active_subscription_per_user ON public.subscriptions USING btree (subscription_user_id)
  WHERE (status = 'active'::public.subscription_status);

CREATE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON public.users
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE POLICY "Allow content read" ON "public"."content"
  FOR SELECT
  TO "anon", "authenticated"
  USING (true);

CREATE POLICY "favorites_owner" ON "public"."favorites"
  FOR ALL
  TO PUBLIC
  USING ((user_id = public.current_app_user_id()))
  WITH CHECK ((user_id = public.current_app_user_id()));

CREATE POLICY "feedback_owner_rw" ON "public"."feedback"
  FOR ALL
  TO PUBLIC
  USING ((user_id = public.current_app_user_id()))
  WITH CHECK ((user_id = public.current_app_user_id()));

CREATE POLICY "feedback_support_all" ON "public"."feedback"
  FOR ALL
  TO "app_support"
  USING (true)
  WITH CHECK (true);

CREATE POLICY "members_admin_all" ON "public"."members"
  FOR ALL
  TO "app_admin"
  USING (true)
  WITH CHECK (true);

CREATE POLICY "members_owner" ON "public"."members"
  FOR ALL
  TO PUBLIC
  USING ((user_id = public.current_app_user_id()))
  WITH CHECK ((user_id = public.current_app_user_id()));

CREATE POLICY "merch_txn_owner" ON "public"."merchandise_transaction"
  FOR ALL
  TO PUBLIC
  USING ((user_id = public.current_app_user_id()))
  WITH CHECK ((user_id = public.current_app_user_id()));

CREATE POLICY "profiles_admin_all" ON "public"."profiles"
  FOR ALL
  TO "app_admin"
  USING (true)
  WITH CHECK (true);

CREATE POLICY "profiles_owner" ON "public"."profiles"
  FOR ALL
  TO PUBLIC
  USING ((user_id = public.current_app_user_id()))
  WITH CHECK ((user_id = public.current_app_user_id()));

CREATE POLICY "review_owner" ON "public"."review"
  FOR ALL
  TO PUBLIC
  USING ((user_id = public.current_app_user_id()))
  WITH CHECK ((user_id = public.current_app_user_id()));

CREATE POLICY "review_public_read" ON "public"."review"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "subscriptions_admin_all" ON "public"."subscriptions"
  FOR ALL
  TO "app_admin"
  USING (true)
  WITH CHECK (true);

CREATE POLICY "subscriptions_owner" ON "public"."subscriptions"
  FOR ALL
  TO PUBLIC
  USING ((subscription_user_id = public.current_app_user_id()))
  WITH CHECK ((subscription_user_id = public.current_app_user_id()));

CREATE POLICY "subscriptions_support_read" ON "public"."subscriptions"
  FOR SELECT
  TO "app_support"
  USING (true);

CREATE POLICY "users_admin_all" ON "public"."users"
  FOR ALL
  TO "app_admin"
  USING (true)
  WITH CHECK (true);

CREATE POLICY "users_self_select" ON "public"."users"
  FOR SELECT
  TO PUBLIC
  USING ((user_id = public.current_app_user_id()));

CREATE POLICY "users_self_update" ON "public"."users"
  FOR UPDATE
  TO PUBLIC
  USING ((user_id = public.current_app_user_id()));

CREATE POLICY "users_support_read" ON "public"."users"
  FOR SELECT
  TO "app_support"
  USING (true);

CREATE POLICY "view_history_owner" ON "public"."view_history"
  FOR ALL
  TO PUBLIC
  USING ((user_id = public.current_app_user_id()))
  WITH CHECK ((user_id = public.current_app_user_id()));

CREATE POLICY "watch_list_owner" ON "public"."watch_list"
  FOR ALL
  TO PUBLIC
  USING ((user_id = public.current_app_user_id()))
  WITH CHECK ((user_id = public.current_app_user_id()));

COMMENT ON TABLE "public"."users" IS 'BP1 - User Account Management';

GRANT EXECUTE ON FUNCTION "public"."current_app_user_id"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

REVOKE ALL ON FUNCTION "public"."is_admin"() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION "public"."is_admin"() TO "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."set_updated_at"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."content" TO "anon", "app_admin";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."content" TO "app_content_manager";

GRANT SELECT ON TABLE "public"."content" TO "app_subscriber";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."content" TO "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."content_license" TO "anon", "app_admin";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."content_license" TO "app_content_manager";

GRANT SELECT ON TABLE "public"."content_license" TO "app_subscriber";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."content_license" TO "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."episodes" TO "anon", "app_admin";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."episodes" TO "app_content_manager";

GRANT SELECT ON TABLE "public"."episodes" TO "app_subscriber";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."episodes" TO "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."favorites" TO "anon", "app_admin";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."favorites" TO "app_subscriber";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."favorites" TO "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."feedback" TO "anon", "app_admin";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."feedback" TO "app_subscriber";

GRANT INSERT, SELECT, UPDATE ON TABLE "public"."feedback" TO "app_support";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."feedback" TO "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."genre" TO "anon", "app_admin";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."genre" TO "app_content_manager";

GRANT SELECT ON TABLE "public"."genre" TO "app_subscriber";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."genre" TO "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."members" TO "anon", "app_admin";

GRANT INSERT, SELECT, UPDATE ON TABLE "public"."members" TO "app_subscriber";

GRANT SELECT ON TABLE "public"."members" TO "app_support";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."members" TO "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."merchandise_product" TO "anon", "app_admin";

GRANT SELECT ON TABLE "public"."merchandise_product" TO "app_subscriber";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."merchandise_product" TO "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."merchandise_transaction" TO "anon", "app_admin";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."merchandise_transaction" TO "app_subscriber";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."merchandise_transaction" TO "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."plans" TO "anon", "app_admin";

GRANT SELECT ON TABLE "public"."plans" TO "app_subscriber", "app_support";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."plans" TO "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "anon", "app_admin";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."profiles" TO "app_subscriber";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."review" TO "anon", "app_admin";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."review" TO "app_subscriber";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."review" TO "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."season" TO "anon", "app_admin";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."season" TO "app_content_manager";

GRANT SELECT ON TABLE "public"."season" TO "app_subscriber";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."season" TO "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."subscriptions" TO "anon", "app_admin";

GRANT INSERT, SELECT, UPDATE ON TABLE "public"."subscriptions" TO "app_subscriber";

GRANT SELECT ON TABLE "public"."subscriptions" TO "app_support";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."subscriptions" TO "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users" TO "anon", "app_admin";

GRANT SELECT ON TABLE "public"."users" TO "app_content_manager";

GRANT SELECT, UPDATE ON TABLE "public"."users" TO "app_subscriber";

GRANT SELECT ON TABLE "public"."users" TO "app_support";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."users" TO "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."view_history" TO "anon", "app_admin";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."view_history" TO "app_subscriber";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."view_history" TO "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."watch_list" TO "anon", "app_admin";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."watch_list" TO "app_subscriber";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."watch_list" TO "authenticated", "postgres", "service_role";

GRANT USAGE ON TYPE "public"."account_status_enum" TO "postgres";

GRANT USAGE ON TYPE "public"."content_type_enum" TO "postgres";

GRANT USAGE ON TYPE "public"."listing_status_enum" TO "postgres";

GRANT USAGE ON TYPE "public"."subscription_status" TO "postgres";

GRANT USAGE ON TYPE "public"."watchlist_status_enum" TO "postgres";

